version: "3.5"

services:
  elasticsearch:
    build: elasticsearch
    env_file: ./docker.env
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  maildev:
    image: djfarrelly/maildev
    env_file: ./docker.env
    depends_on:
      - php
    ports:
      - 1080:80

  mysql:
    image: mariadb
    env_file: ./docker.env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    build: nginx
    env_file: ./docker.env
    ports:
      - 443:443
    volumes:
      - ${MAGENTO_ROOT}:/var/www/html:rw,delegated
      # Custom configuration
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    tty: true

  php:
    build:
      context: ./php/${PHP_VERSION}
    env_file: ./docker.env
    volumes:
      - ${MAGENTO_ROOT}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/${PHP_VERSION}/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
    tty: true

  redis:
    image: redis:3.2-alpine
    env_file: ./docker.env
    volumes:
      - redis:/data
    tty: true

  phpmyadmin:
    build: ./phpmyadmin
    env_file:
      - ./docker.env
    ports:
     - 8080:80

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
