version: "3.5"

services:
  elasticsearch:
    build: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  maildev:
    image: djfarrelly/maildev
    env_file: ./docker.env
    depends_on:
      - php
    ports:
      - 1080:80

  mysql:
    image: mariadb
    env_file: ./docker.env
    ports:
      - 3307:3307
    volumes:
      - mysql:/var/lib/mysql
      - ./mysqldump:/mysqldump
    tty: true

  nginx:
    build: nginx
    env_file: ./docker.env
    ports:
      - 443:443
    volumes:
      - ${MAGENTO_ROOT}:/var/www/html:rw,delegated
      # Custom configuration
      - ./nginx/servers/nginx${MAGENTO_VERSION}.conf:/etc/nginx/conf.d/custom.conf:ro
    tty: true

  php:
    build:
      context: ./php/${PHP_VERSION}
    env_file: ./docker.env
    volumes:
      - ${MAGENTO_ROOT}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/${PHP_VERSION}/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
      # Mage cache clean
      - ./php/${PHP_VERSION}/mage-cache-clean:/var/www/html/vendor/mage-cache-clean
    tty: true
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1

  redis:
    image: redis:3.2-alpine
    env_file: ./docker.env
    volumes:
      - redis:/data
    tty: true

  phpmyadmin:
    build: ./phpmyadmin
    env_file:
      - ./docker.env
    ports:
     - 8080:80

volumes:
  elasticsearch: {}
  mysql: {}
  redis: {}
